version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      # Python
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - make html -e SPHINXOPTS='-D language="en"'
artifacts:
  files:
    - "**/*"
  base-directory: "build/html"
